Feat/#57
GDSC-SKHU/2023-DontWorry-SolutionChallenge pull request #81
Opened 2023-03-14 16:39 UTC by zoeyourlife

## Description

> 구현 및 작업 내용을 적어주세요.

- selectCountry 컴포넌트 구현 
- 첫번째 컴포넌트는 select, option 태그만을 사용해서 select 구현.
- 두번째 컴포넌트는 Select Box를 커스텀형식으로 만들어봤습니다.

## Important content

> 주의 깊게 봐야 하거나 말하고 싶은 점을 적어주세요.

- 두번째 컴포넌트에서 옵션값을 인덱스 or 키값으로 연결시킬 수 있는 지 궁금함
- 옵션에 각 나라별 국기를 직접 넣는 방법을 찾아보려고 했지만 우선적으로 찾지는 못함
- jquery 또는 다른 라이브러리를 나라가 많지도 않아서 고민이 됨 < 의견 바랍니다.
- 첫번째 컴포넌트의 option은 css를 꾸밀 수 없는 단점이 있음 라이브러리 사용 or select 커스텀 해야함

2023-03-15 01:27 UTC, jaegwans approved these changes
👍고생하셨습니다.

2023-03-15 14:22 UTC, hanseulhee requested changes
`두번째 컴포넌트에서 옵션값을 인덱스 or 키값으로 연결시킬 수 있는 지 궁금함`

constants로 만들어서 [{id: 1, link: "japan", title: "JP, Japan"}, ...]  어떠한 나라를 클릭 시
Link href=help/${country.link} 하는 방법이 있을 것 같네요

`옵션에 각 나라별 국기를 직접 넣는 방법을 찾아보려고 했지만 우선적으로 찾지는 못함`

사용자가 직접 국기를 넣는 방법 말씀하시는 거라면 안 해도 될 것 같은데 어떤가요?

`jquery 또는 다른 라이브러리를 나라가 많지도 않아서 고민이 됨 < 의견 바랍니다.`

다른 라이브러리를 사용하는 것이 고민이 된다는 말씀이신가요?

`첫번째 컴포넌트의 option은 css를 꾸밀 수 없는 단점이 있음 라이브러리 사용 or select 커스텀 해야함`

안해도 보기 좋아서 이건 고민 안해도 될 것 같아요

2023-03-15 14:22 UTC, hanseulhee commented on src/components/SelectCountry/CountryDropDown.tsx
> +  countries: string[];
interface 말고 type을 쓰신 이유가 궁금해요

2023-03-15 14:22 UTC, hanseulhee commented on src/components/SelectCountry/CountryDropDown.tsx
> +    <>
이건 지워주세요!

2023-03-15 14:22 UTC, hanseulhee commented on src/components/SelectCountry/CountryDropDown.tsx
> +const CountryDropDown: React.FC<CountryDropDownProps> = ({
React.FC를 사용하신 이유는 뭔가요 ?

저희 main 브랜치에는 React.FC를 쓴 게 없어서 다른 이유가 없다면 안쓰는 게 좋을 것 같아요

2023-03-15 14:22 UTC, hanseulhee commented on src/components/SelectCountry/index.tsx
> +  background-color: #fff;
이 색상은 theme에 있어요!

2023-03-15 14:22 UTC, hanseulhee commented on src/components/SelectCountry/index.tsx
> +  const [showDropDown, setShowDropDown] = useState<boolean>(false);
저희 arrow function 말고 function으로 통일하고 있어요!

2023-03-15 14:22 UTC, hanseulhee commented on src/components/SelectCountry/index.tsx
> +              countrySelection={countrySelection}
```suggestion
              toggleDropDown={() => toggleDropDown()}
              countrySelection={countrySelection}
```
로 해줘도 될 것 같아요

2023-03-15 14:22 UTC, hanseulhee commented on src/components/SelectCountryT/index.tsx
> +function SelectCountryT() {
`SelectCountryT`

라는 이름이 무엇을 뜻하는 지 잘 모르겠어요 
임시로 해놓으신 걸까요 ?!

2023-03-15 14:22 UTC, hanseulhee commented on src/components/SelectCountry/CountryDropDown.tsx
> +        {countries.map((country: string, index: number): JSX.Element => {
이미 countries가 string배열이기 때문에 타입을 명시 안해도 될 것 같아요
```suggestion
     {countries.map((country, index): => {
```

2023-03-15 14:22 UTC, hanseulhee commented on src/components/SelectCountry/index.tsx
> +  border-radius: ${({ theme }) => theme.borderRadius.imgCard};
css는 비슷한 속성 끼리 묶는 게 나중에도 더 보기 좋을 것 같지 않나용 ?

```suggestion
  user-select: none;
  
  font-weight: ${({ theme }) => theme.fontWeight.normal};
  font-size: 0.85rem;
  line-height: 1.5;
  
  border: 0.125rem solid transparent;
  border-radius: ${({ theme }) => theme.borderRadius.imgCard};
```

2023-03-15 14:22 UTC, hanseulhee commented on src/components/SelectCountryT/index.tsx
> +    background-repeat: no-repeat;
이건 적용이 되고 있나요 ? image가 pr에 안올라왔는데

2023-03-15 14:53 UTC, zoeyourlife commented on src/components/SelectCountryT/index.tsx
> +    background-repeat: no-repeat;
Important content 두 번째 부분에 제가 말하고 싶었던 내용이 이 부분입니다. 
그 옵션 선택 왼쪽에 자그맣게 국가 아이콘을 넣고 싶은데 그 시도를 한 흔적입니다 . . 국기 사진은
올리지 않고 커밋했습니다 !

2023-03-15 15:07 UTC, zoeyourlife commented on src/components/SelectCountry/CountryDropDown.tsx
> +        {countries.map((country: string, index: number): JSX.Element => {
넵.. 따로 또 지정해줘야 되는 줄 알았습니다

2023-03-15 15:07 UTC, zoeyourlife commented on src/components/SelectCountryT/index.tsx
> +function SelectCountryT() {
넵 임시 컴포넌트로 만들어 둔 것이에요

2023-03-15 15:09 UTC, zoeyourlife commented on src/components/SelectCountry/CountryDropDown.tsx
> +const CountryDropDown: React.FC<CountryDropDownProps> = ({
잘 모르고 사용해서 찾아봤는데, 안티패턴이라고 지양하라고 하네요 ,, 감사합니다 !

2023-03-15 15:15 UTC, zoeyourlife commented on src/components/SelectCountry/CountryDropDown.tsx
> +  countries: string[];
제가 처음에 생각했을 때는 type 이든 interface든 상관없을 거라 생각했는데, 
저희 컨벤션도 interface로 하기로 했었고, type은 써야할 때 아니면 쓰지 않는게 좋다는 걸 다시 알았습니다 . .

2023-03-15 15:20 UTC, zoeyourlife commented on src/components/SelectCountry/index.tsx
> +  border-radius: ${({ theme }) => theme.borderRadius.imgCard};
고치겠습니다!

2023-03-15 15:41 UTC, zoeyourlife commented
> link: "japan", title: "JP, Japan"}, ...] 어떠한 나라를 클릭 시
> Link href=help/${country.link} 하는 방법이 있을 것 같네요

> 아 이해됐습니다 . .감사함니다

2023-03-15 16:07 UTC, hanseulhee approved these changes
Gooooooooooooooooooooood 😎

2023-03-15 16:07 UTC, hanseulhee commented on src/components/SelectCountry/CountryDropDown.tsx
> +            }}
```suggestion
            onClick={() => {
              onClickHandler(country);
            }}
```

다른 곳들도 이런 게 있는데 void를 쓰시는 이유가 뭔가요?

2023-03-15 16:07 UTC, hanseulhee commented on src/components/SelectCountry/index.tsx
> +  const outFoucsHandler = (e: React.FocusEvent<HTMLButtonElement>) => {
```suggestion
import { FocusEvent } from "react";

  const outFoucsHandler = (e: FocusEvent<HTMLButtonElement>) => {
```

로 아래도 다 통일하는 게 어떤가요 ?? 저는 다 이렇게 해왔어서 맞추면 좋을 것 같아요 ~!

2023-03-15 17:23 UTC, zoeyourlife commented on src/components/SelectCountry/index.tsx
> +  const outFoucsHandler = (e: React.FocusEvent<HTMLButtonElement>) => {
넵 참고해서 다시 리퀘 할게요 !

2023-03-16 13:46 UTC, hanseulhee approved these changes
굿굿 !!!!

2023-03-16 13:46 UTC, hanseulhee commented on src/components/SelectCountry/index.tsx
> +function SelectCountryT() {
이거 SelectCountryT -> SelectCountry
로 수정해주시고 머지하면 될 것 같아요 ~~

2023-03-16 14:23 UTC, zoeyourlife commented on src/components/SelectCountry/index.tsx
> +function SelectCountryT() {
넵 !

2023-03-16 14:27 UTC, merged